version: '3'
services:
    mongo:
        image: mongo:4.1.7-xenial
        restart: always
        volumes:
            - ./mongo/db:/data/db
        ports:
            - 27017:27017
        environment:
            - MONGO_INITDB_ROOT_USERNAME=mdbroot
            - MONGO_INITDB_ROOT_PASSWORD=mdbpass
            - MONGO_INITDB_DATABASE=graphql_demo
        networks:
            - graphqlnet

    mongo-express:
        image: mongo-express:0.49.0
        restart: always
        ports:
            - 8081:8081
        environment:
            - ME_CONFIG_OPTIONS_EDITORTHEME=ambiance
            - ME_CONFIG_MONGODB_ADMINUSERNAME=mdbroot
            - ME_CONFIG_MONGODB_ADMINPASSWORD=mdbpass
        depends_on:
            - mongo
        links:
            - mongo
        networks:
            - graphqlnet

    server:
        build: ./node/server
        image: node-server:0.1
        restart: always
        command: npm run dev
        volumes:
            - ./node/server:/usr/src/app
            - server_node_modules:/usr/src/app/node_modules # https://stackoverflow.com/questions/30043872/docker-compose-node-modules-not-present-in-a-volume-after-npm-install-succeeds
        ports:
            - 4000:4000
        depends_on:
            - mongo
        networks:
            - graphqlnet

    client:
        build: ./node/client
        image: node-client:0.1
        restart: always
        command: npm run start
        volumes:
            - ./node/client:/usr/src/app
            - client_node_modules:/usr/src/app/node_modules # https://stackoverflow.com/questions/30043872/docker-compose-node-modules-not-present-in-a-volume-after-npm-install-succeeds
        ports:
            - 3000:3000
        networks:
            - graphqlnet

volumes:
    server_node_modules:
    client_node_modules:

networks:
    graphqlnet:
        driver: bridge
        driver_opts:
            com.docker.network.enable_ipv6: "false"
        ipam:
            driver: default
            config:
                - subnet: 172.16.238.0/24
