version: '3'
services:
    mongo:
        image: mongo:4.1.7-xenial
        restart: always
        volumes:
            - ./mongo/db:/data/db
        ports:
            - 27017:27017
        environment:
            - MONGO_INITDB_ROOT_USERNAME=mdbroot
            - MONGO_INITDB_ROOT_PASSWORD=mdbpass
            - MONGO_INITDB_DATABASE=graphql_demo
        networks:
            - graphqlnet

    mongo-express:
        image: mongo-express:0.49.0
        restart: always
        ports:
            - 8081:8081
        environment:
            - ME_CONFIG_OPTIONS_EDITORTHEME=ambiance
            - ME_CONFIG_MONGODB_ADMINUSERNAME=mdbroot
            - ME_CONFIG_MONGODB_ADMINPASSWORD=mdbpass
        depends_on:
            - mongo
        links:
            - mongo
        networks:
            - graphqlnet

    graphql-server:
        build:
            context: ./graphql/server
            args:
                - 'INSTALL_DIR=$SERVER_INSTALL_DIR'
        image: graphql-server:0.1
        restart: always
        command: npm run dev
        volumes:
            - ./graphql/server:${SERVER_INSTALL_DIR}
            - server_node_modules:${SERVER_INSTALL_DIR}/node_modules # https://stackoverflow.com/questions/30043872/docker-compose-node-modules-not-present-in-a-volume-after-npm-install-succeeds
        ports:
            - 4000:4000
        depends_on:
            - mongo
        networks:
            - graphqlnet

    graphql-client:
        build:
            context: ./graphql/client
            args:
                - 'INSTALL_DIR=$CLIENT_INSTALL_DIR'
        image: graphql-client:0.1
        restart: always
        command: npm run start
        volumes:
            - ./graphql/client:${CLIENT_INSTALL_DIR}
            - client_node_modules:${CLIENT_INSTALL_DIR}/node_modules # https://stackoverflow.com/questions/30043872/docker-compose-node-modules-not-present-in-a-volume-after-npm-install-succeeds
        ports:
            - 3000:3000
        networks:
            - graphqlnet

volumes:
    server_node_modules:
    client_node_modules:

networks:
    graphqlnet:
        driver: bridge
        driver_opts:
            com.docker.network.enable_ipv6: "false"
        ipam:
            driver: default
            config:
                - subnet: 172.16.238.0/24
